# Generated by Django 5.0 on 2024-01-22 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderBlog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cliente',
            new_name='Clientes',
        ),
    ]
