# Generated by Django 5.0 on 2024-01-31 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coderBlog', '0002_rename_cliente_clientes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profesores',
            name='celular',
        ),
    ]
